### ISSUE TITLE
add PostgreSQLIndexer

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina-hub#6845]
As part of https://github.com/jina-ai/internal-tasks/issues/40

As part of https://github.com/jina-ai/jina/pull/2154

**SUBTASK**

- [x] Docker image running with a Dummy Executor -- get PostgreSQL Docker image and install Jina in it
- [x] Executor performs CRUD ops 
- [x] Executor performs DumpRequest

Should inherit from

```python
from jina.executors.indexers import BaseIndexer


class BaseDBMSIndexer(BaseIndexer):
    def add(self, ids, vecs, metas, *args, **kwargs):
        raise NotImplementedError

    def update(self, ids, vecs, metas, *args, **kwargs):
        raise NotImplementedError

    def delete(self, ids, *args, **kwargs):
        raise NotImplementedError

    def dump(self, uri, shards, formats):
        raise NotImplementedError
```

**Comment by carlosb1** [comment]
It could be useful to do something similar for other SQL services like Spark?

**Comment by cristianmtr** [comment]
Done in https://github.com/jina-ai/jina-hub/pull/6897/
